# The api key, secret key, and canvas page name are required to get started
# Tunnel configuration is only needed if you are going to use the facebooker:tunnel Rake tasks
# Your callback url in Facebook should be set to http://public_host:public_port
# If you're building a Facebook connect site, 
#    change the value of set_asset_host_to_callback_url to false
# To develop for the new profile design, add the following key..
# api: new
# remove the key or set it to anything else to use the old facebook design.
# This should only be necessary until the final version of the new profile is released.

development:
  api_key: 2c930f0e1a5b66bce29628c5ca293a2d 
  secret_key: 6a14b508f28b31e430420f6a34910dbe 
  canvas_page_name: byobalpha
  callback_url: http://web1.tunnlr.com:10731
  pretty_errors: true
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username: tunnlr1142
    public_host: ssh1.tunnlr.com
    public_port: 10731
    local_port: 3000
    server_alive_interval: 0

test:
  api_key: 91ccefcd5e7d5201afe11818f5af5c5d 
  secret_key: 4ec789f14d6dfe662aff4e827fc7d781 
  canvas_page_name: beyourownbus
  callback_url: http://www.harishtella.info
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0

production:
  api_key: 91ccefcd5e7d5201afe11818f5af5c5d 
  secret_key: 4ec789f14d6dfe662aff4e827fc7d781 
  canvas_page_name: beyourownbus
  callback_url: http://www.harishtella.info
  set_asset_host_to_callback_url: true   
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0
